version: "3.3"

services:
# multiparty-meeting
  mm:
    env_file: .env
    image: misi/mm:${TAG}
    build:
      args:
        - BASEDIR=${BASEDIR}
        - MM=${MM}
        - NODE_ENV=${NODE_ENV}
        - SERVER_DEBUG=${SERVER_DEBUG}
      context: ./
    restart: always
    volumes:
      - ./configs/server:${BASEDIR}/${MM}/server/config
      - ./configs/app:${BASEDIR}/${MM}/server/public/config
      - ./certs:${BASEDIR}/${MM}/server/certs
      - ./images:${BASEDIR}/${MM}/server/public/images
    ports:
      - "80:80"
      - "443:443"
      - "40000-49999:40000-49999/udp"
    network_mode: "host"
    stdin_open: true
    tty: true
  redis:
    image: redis
    network_mode: "host"
    entrypoint: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    volumes:
      - ./configs/redis:/usr/local/etc/redis
  ouroboros:
    container_name: ouroboros
    hostname: ouroboros
    image: pyouroboros/ouroboros
    environment:
      - CLEANUP=false
      - INTERVAL=300
      - LOG_LEVEL=info
      - SELF_UPDATE=true
      - IGNORE=mongo influxdb postgres mariadb
      - TZ=Europe/Budapest
      - CRON="* 2 * * *"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
